name: Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  run:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Create var dir
        run: mkdir var

      - name: Composer install
        run: composer install --optimize-autoloader

      - name: Codestyle
        run: composer php-cs

      - name: Psalm
        run: composer psalm

      - name: Tests
        run: composer test
